### ISSUE TITLE
Not working on AWS Lambda

### ISSUE THREAD

**Issue by awolad** [aboutdavid/quizlet-fetcher#1]
It's working locally but getting an error when using it inside AWS lambda.

`Failed to fetch the quizlet cards. Status code: 403`

**Comment by aboutDavid** [comment]
Quizlet has a anti-bot firewall setup (sort of like CloudFlare). The only way I could really suggest fixing it is getting a proxy.

**Comment by awolad** [comment]
@aboutDavid Thanks for your reply. Could you please give me an example?

**Comment by aboutDavid** [comment]
> @aboutDavid Thanks for your reply. Could you please give me an example?

Sorry, I don't really use proxies, but here is something I threw together

```js
const quizlet = require("quizlet-fetcher")
const fetch = require("node-fetch-with-proxy");

fetch("https://quizlet.com/...")
  .then(res => res.text())
  .then(html => {
  var flashcard = quizlet(html)
  // do something with "flashcard"
});
```

**Comment by awolad** [comment]
@aboutDavid I'll try it, thanks.

**Comment by aboutdavid** [comment]
Let me know if something is not working as intended
